### ISSUE TITLE
Developing a QC script for the SLA data

### ISSUE THREAD

**Issue by bpbond** [PNNL-PREMIS/SULI#17]
Tasks here (please check off when completed):

**Data**

- [x] @lilliehaddock (by yourself or in conjunction with others) - create a new branch, enter the leaf mass data from today into `SLA Data.csv`, open a PR
- [x]  @marideeweber and/or @hmoore28 -  review, request any needed changes, approve, and merge

**Reading in data and computing SLA** 

We'd prefer that you _each_ do the following, in your own branches. But if you want to work on a common branch and split the tasks, that's fine too.

- [x] Open a new branch. Extend the `SLA.R` script to compute _specific leaf area_ (SLA), which is area divided by mass. Use a `dplyr` pipeline to do this
- [x] Visualize the data: make a box plot for each species' SLA values, overlaying the box plot with the individual data points. Label the points by tree tag number (see `?geom_text`)
- [x] Paste the plot(s) in a comment below and we'll discuss/look for outliers or problems.

**Joining**

- [x] Next, read in (`read_csv`) the `ss-inventory.csv` tree inventory file. Summarize it. Write a `dplyr` pipeline that prints a nice table of the mean and standard deviation of DBH, by plot and tree species **for live maple trees only**. It should look something like this:
```
# A tibble: 3 x 4
# Groups:   Plot [?]
  Plot    Species    mn    sd
  <chr>   <chr>   <dbl> <dbl>
1 Control ACRU     20.3  9.94
2 Fresh   ACRU     28.0 13.7 
3 Salt    ACRU     21.7 10.4 
```

- [x] Select just the `Plot`, `Species`, and `Tag` columns. Call this new dataset `inventory_small`

- [x] The next pipeline should _join_ the `SLA` and `inventory_small` datasets, probably using `left_join()`.

- [x] Plot the SLA data by species, faceting by plot.

Please open a PR with this code. In the PR comments, paste in the beginning of the output table and plot(s).

**Comment by haileymoore** [comment]
A box plot showing the SLA values for each species with individual data points overlayed and labeled by tag #. The #'s are offset horizontally, but the points are too close together to be able to separate them vertically
![SLA_boxplot](https://user-images.githubusercontent.com/51137327/59880375-dcba4980-937a-11e9-87c5-712e6b918574.png)

**Comment by bpbond** [comment]
@hmoore28 Nice job! 👏  Cool. Re the overlapping text, remember `geom_jitter()` and @stephpenn1 has experience with `ggrepel()` which I believe 'repels' labels (but not points) from each other for readability. Can you color by canopy position please?

Interesting that the SLA values for most species cluster pretty tightly, with some _significant_ exceptions. @lilliehaddock we're going to want to look closely at outliers, e.g. samples from tree 1560.

**Comment by haileymoore** [comment]
The box plot is now colored by canopy position. I tried both `geom_jitter()` and `geom_text_repel()`. When using both the box plot and overlaying each individual data point, the data points that are outliers and represented individually show up twice - once as an outlier and once as an individual data point, i.e. 1739 in NYSY. 

`geom_jitter()` looks to move the points around but not the labels. 
![boxplot_position_jitter](https://user-images.githubusercontent.com/51137327/59926999-7e887780-9409-11e9-85bc-20d65d4268fb.png)

With `ggrepel()`, the labels are actually readable, but there are still so many that the plot is super messy. 

![boxplot_canopy_color_ggrepel](https://user-images.githubusercontent.com/51137327/59927000-7e887780-9409-11e9-9b53-366748b95f73.png)

**Comment by bpbond** [comment]
Thanks @hmoore28 ! Nice. Interesting to see those differences. Again, @lilliehaddock we're going to want to check some of those outliers (e.g. 1739, 1621, 1560): wrong species? Mistake in data entry? Or just a goofy leaf, i.e. an oddball but a real one?

**Comment by lilliehaddock** [comment]
I used `geom_text_repel()` here, but it still looks cluttered. 
![Rplot SLA by species and position](https://user-images.githubusercontent.com/51174695/59928428-b5ac5800-940c-11e9-9346-760017603212.png)

I'll look into the outliers and see what is going on there.

**Comment by marideeweber** [comment]
![Weber SLA](https://user-images.githubusercontent.com/51207967/59928925-be515e00-940d-11e9-9f72-dbc2e959020a.png)

**Comment by bpbond** [comment]
Very nice! Maybe faceting by tree species would be clearer? Also, why do your plots have an `NA` tree species but Hailey's doesn't? 🤔

**Comment by lilliehaddock** [comment]
The "by 1802" LITU doesn't have a species in the inventory so it was showing up as NA! Haley helped me fix that issue.

**Comment by lilliehaddock** [comment]
Below is the SLA plot faceted by plot. 
![SLA by species, plot, and tag](https://user-images.githubusercontent.com/51174695/59934516-b8617a00-9419-11e9-831d-aabd7ef2e38f.png)

This is a more simplified version with no tag labeling. Its interesting to see how SLA varies by plot!!
![SLA by plot](https://user-images.githubusercontent.com/51174695/59934517-b8fa1080-9419-11e9-989e-5ff458cc3e08.png)

Here is the SLA faceted by plot. I'm not sure how to remove the CAGL8 plot though!! 
![SLA by species and plot](https://user-images.githubusercontent.com/51174695/59934930-af24dd00-941a-11e9-84d9-526d7bebf8bf.png)

**Comment by bpbond** [comment]
Interesting! Thanks.
