### ISSUE TITLE
Reading list

### ISSUE THREAD

**Issue by bpbond** [PNNL-PREMIS/SULI#30]
Remember, for most of these is _not_ to spend hours reading extremely closely, but rather to familiarize yourself with scientific issues and underlying science.
 
The important of open baseline data:
https://onlinelibrary.wiley.com/doi/10.1111/gcb.14442
http://dx.doi.org/10.1111/j.1365-2486.2012.02693.x

Using SLA data to calculate canopy leaf area:
http://dx.doi.org/10.1093/treephys/22.14.993
https://www.sciencedirect.com/science/article/pii/S0168192305000055

Global importance of SLA and other traits vis-a-vis plant distribution and growth:
https://www.nature.com/articles/nature16489
https://besjournals.onlinelibrary.wiley.com/doi/pdf/10.1111/1365-2745.12221
https://onlinelibrary.wiley.com/doi/full/10.1111/j.1461-0248.2012.01852.x

...and community assembly:
https://onlinelibrary.wiley.com/doi/full/10.1111/jvs.12041
https://academic.oup.com/aob/article/108/7/1337/135123

Importance of SLA and traits for global models:
http://dx.doi.org/10.1029/2011JG001913

**Comment by stephpenn1** [comment]
Moving this to `PREMIS-SLA`
