### ISSUE TITLE
What is the random-sampling script doing?

### ISSUE THREAD

**Issue by bpbond** [PNNL-PREMIS/SULI#4]
1. Download [GitHub Desktop](https://desktop.github.com), if you haven't already.
2. [Clone](https://help.github.com/en/articles/cloning-a-repository) this repository.
3. Open the RStudio file and run `sla_sampling.R`. What happens? Why?
4. If the script is randomly sampling, _why does it always return the same results?_

**Comment by marideeweber** [comment]
The script returns the same results due to the "set.seed()" function.  Using the function set.seed(12345) ensures that the randomly generated results are reproducible.  Changing the function to set.seed(12344) will produce a new random order.

**Comment by bpbond** [comment]
@marideeweber Right! 👏  

...and that is really important! We want to randomize, but _also_ to be able to reproduce our results. R (and most computer languages) use a pseudo-random number generator, and `set.seed()` gives this generator the "seed" to start from.

**Comment by haileymoore** [comment]
`set.seed()` is what causes random_inv to produce the same random sampling every time. By setting the seed, we're able to ensure reproducibility in our code

**Comment by lilliehaddock** [comment]
According to the R Help page, `set.seed` allows for reproducible work from the uniform random-number generator. This is helpful, especially in our case, because it allows us to create the same sampling list with the order we should be sampling over and over again. We love reproducible science!
